In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
input_features=np.array([[0,0],[0,1],[1,0],[1,1]])

In [6]:
print(input_features.shape)
input_features

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [10]:
to=np.array([[0,1,1,1]])
to=to.reshape(4,1)
print(to.shape)
to

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [12]:
w=np.array([[0.2],[0.3]])
print(w.shape)
w

(2, 1)


array([[0.2],
       [0.3]])

In [13]:
bais=0.5
lr=0.5

In [15]:
def sigmoid(x):
    return 1/(1=np.exp(-x))

SyntaxError: invalid syntax (<ipython-input-15-1793530d478e>, line 2)